// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PdfSelectorController from "./pdf_selector_controller"
application.register("pdf-selector", PdfSelectorController)

import PdfUploadController from "./pdf_upload_controller"
application.register("pdf-upload", PdfUploadController)

import PdfViewerController from "./pdf_viewer_controller"
application.register("pdf-viewer", PdfViewerController)
