// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import PdfViewerController from "./pdf_viewer_controller"
import PdfSelectorController from "./pdf_selector_controller"
application.register("hello", HelloController)
application.register("pdf-viewer", PdfViewerController)
application.register("pdf-selector", PdfSelectorController)
